aws_region = "us-east-1"
bastion_key_name = "datagov-nhunt"
xbastion_ami = "ami-fce3c696"
bastion_instance_type = "t2.nano"
bastion_subnet_id = "subnet-29c04203"
bastion_security_group_id = "sg-ba1b05c1"
