
stage 'Create Stack'

node("master") {
    checkout scm
    dir("terraform/") {
        def source_dir = "${pwd()}"
        sh "ls -al"
        sh "chmod 777 '${source_dir}/bin/create-stack.sh'"
        sh "ls -al '${source_dir}/bin'"
        sh "'${source_dir}/bin/create-stack.sh' --destroy -v pilot '${env.BRANCH_NAME}'"
    }
}