
stage 'Create Stack'

node("master") {
    def script = "${pwd()}/terraform/bin/create-stack.sh"
    checkout scm
    dir("terraform/") {
        sh """
            chmod 777 '${script}'
            ls -al '${script}'
            '${script}' --destroy -v pilot '${params.BRANCH}'
        """
    }
}