---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: php-fixes-bionic
    image: ubuntu:bionic
    privileged: true
    command: "/sbin/init"
provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint: |
    set -e
    flake8
