---
name: Add New Issues to GH Projects

on:   # yamllint disable-line rule:truthy
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: 'https://github.com/orgs/GSA/projects/11/views/1'
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
