---
# This playbook is used in development to debug an individual variable on a
# particular host. Specify the host you want to debug, the variable name, and
# the inventory you want to use.
#
#     $ ansible-playbook debug.yml -i inventories/staging -e debug_variable=catalog_db_user --limit catalogharvester1d.dev-ocsit.bsp.gsa.gov
#
# Caveats: some variables depend on the facts gathered by ansible and that
# won't happen in local development without connecting to the host.
# Alternatively, if you have access to the host (e.g. on a jumpbox) you can run
# this one-liner instead.
#
#     $ ansible -m debug -a 'msg=variable_name={{ variable_name }}' $hostname

- name: Debug
  hosts: all
  gather_facts: false
  tasks:
    - name: debug variable
      debug:
        msg: "{{ debug_variable }}={{ lookup('vars', debug_variable) }}"
      delegate_to: localhost
      run_once: true
