---
name: App Restart Template

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environ:
        required: true
        type: string
      app_url:
        required: false
        type: string
      app_names:
        required: true
        type: string
    secrets:
      CF_SERVICE_USER:
        required: true
      CF_SERVICE_AUTH:
        required: true

jobs:
  precheck:
    name: verify CF creds
    runs-on: ubuntu-latest
    steps:
      - name: verify CF creds presence (no value output)
        run: |
          if [ -n "${{ secrets.CF_SERVICE_USER }}" ] && [ -n "${{ secrets.CF_SERVICE_AUTH }}" ]; then
            echo "CF creds present"
          else
            echo "CF creds missing" && exit 1
          fi
  attempt1:
    name: restart (${{ inputs.environ }}) attempt 1
    needs: precheck
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.app_names) }}
    uses: ./.github/workflows/restart-attempt.yml
    secrets:
      CF_SERVICE_USER: ${{ secrets.CF_SERVICE_USER }}
      CF_SERVICE_AUTH: ${{ secrets.CF_SERVICE_AUTH }}
    with:
      environ: ${{ inputs.environ }}
      app_url: ${{ inputs.app_url }}
      app: ${{ matrix.app }}
      sleep_before: false
