---
name: App Restart Template

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environ:
        required: true
        type: string
      app_url:
        required: false
        type: string
      app_names:
        required: true
        type: string

jobs:
  attempt1:
    name: restart (${{ inputs.environ }}) attempt 1
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.app_names) }}
    uses: ./.github/workflows/restart-attempt.yml
    with:
      environ: ${{ inputs.environ }}
      app_url: ${{ inputs.app_url }}
      app: ${{ matrix.app }}
      sleep_before: false
