name: Static Site QA Template

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  qa:
    name: QA Static Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
      - name: Fetch Dependencies
        shell: bash
        run: npm ci
      - name: Check Broken Links
        shell: bash
        run: npm run qa
